"""add biometric_id to employees

Revision ID: 01ee345f8ac2
Revises: c9f05440e7f5
Create Date: 2026-06-12 10:12:00.831143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ee345f8ac2'
down_revision: Union[str, None] = 'c9f05440e7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('biometric_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_employees_biometric_id'), 'employees', ['biometric_id'], unique=True)
    # Populate existing biometric_id with machine_employee_id values
    op.execute("UPDATE employees SET biometric_id = machine_employee_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_biometric_id'), table_name='employees')
    op.drop_column('employees', 'biometric_id')
    # ### end Alembic commands ###

