"""Add pvi, bhyt, emails, notes, uploads

Revision ID: 2484ee4e233f
Revises: c24b11595164
Create Date: 2026-07-03 14:45:08.564392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2484ee4e233f'
down_revision: Union[str, None] = 'c24b11595164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('pvi_insurance', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('health_insurance_number', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('company_email', sa.String(length=150), nullable=True))
    op.add_column('employees', sa.Column('personal_email', sa.String(length=150), nullable=True))
    op.add_column('employees', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('cccd_url', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('contract_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'contract_url')
    op.drop_column('employees', 'cccd_url')
    op.drop_column('employees', 'notes')
    op.drop_column('employees', 'personal_email')
    op.drop_column('employees', 'company_email')
    op.drop_column('employees', 'health_insurance_number')
    op.drop_column('employees', 'pvi_insurance')
    # ### end Alembic commands ###

