"""Add departments

Revision ID: 2b1e90f7f3ca
Revises: 38972f4b0532
Create Date: 2026-07-03 16:12:32.305616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1e90f7f3ca'
down_revision: Union[str, None] = '38972f4b0532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###

