"""Change cccd and contract url to Text

Revision ID: 38972f4b0532
Revises: 2484ee4e233f
Create Date: 2026-07-03 15:42:31.713947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38972f4b0532'
down_revision: Union[str, None] = '2484ee4e233f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'cccd_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('employees', 'contract_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###
    
    # Data migration: convert existing strings to JSON arrays
    connection = op.get_bind()
    import json
    
    # Update cccd_url
    results = connection.execute(sa.text("SELECT id, cccd_url, contract_url FROM employees")).fetchall()
    for row in results:
        emp_id = row[0]
        cccd_val = row[1]
        contract_val = row[2]
        
        new_cccd = None
        new_contract = None
        
        if cccd_val and not cccd_val.startswith('['):
            new_cccd = json.dumps([cccd_val])
        if contract_val and not contract_val.startswith('['):
            new_contract = json.dumps([contract_val])
            
        if new_cccd or new_contract:
            update_stmt = "UPDATE employees SET "
            params = {"id": emp_id}
            sets = []
            if new_cccd:
                sets.append("cccd_url = :cccd")
                params["cccd"] = new_cccd
            if new_contract:
                sets.append("contract_url = :contract")
                params["contract"] = new_contract
                
            update_stmt += ", ".join(sets) + " WHERE id = :id"
            connection.execute(sa.text(update_stmt), params)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'contract_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('employees', 'cccd_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
