"""add_department_bonus_config

Revision ID: 54c9148a2c11
Revises: 9c8513f9d9a0
Create Date: 2026-07-07 14:22:22.486994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c9148a2c11'
down_revision: Union[str, None] = '9c8513f9d9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_bonus_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_bonus_configs_department_id'), 'department_bonus_configs', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_bonus_configs_period'), 'department_bonus_configs', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_bonus_configs_period'), table_name='department_bonus_configs')
    op.drop_index(op.f('ix_department_bonus_configs_department_id'), table_name='department_bonus_configs')
    op.drop_table('department_bonus_configs')
    # ### end Alembic commands ###

