"""Add end_period to department bonus configs

Revision ID: 637b01338b98
Revises: e863d7acf11b
Create Date: 2026-07-09 11:05:34.497417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637b01338b98'
down_revision: Union[str, None] = 'e863d7acf11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_bonus_configs', sa.Column('end_period', sa.String(length=7), nullable=True))
    op.create_index(op.f('ix_department_bonus_configs_end_period'), 'department_bonus_configs', ['end_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_bonus_configs_end_period'), table_name='department_bonus_configs')
    op.drop_column('department_bonus_configs', 'end_period')
    # ### end Alembic commands ###

