"""add_performance_indexes

Revision ID: 6ab2ee9049c6
Revises: c95d1beea36b
Create Date: 2026-06-29 16:07:17.868632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab2ee9049c6'
down_revision: Union[str, None] = 'c95d1beea36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendance_daily_period_end'), 'attendance_daily', ['period_end'], unique=False)
    op.create_index(op.f('ix_attendance_daily_period_start'), 'attendance_daily', ['period_start'], unique=False)
    op.create_index(op.f('ix_off_requests_end_date'), 'off_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_off_requests_start_date'), 'off_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_off_requests_status'), 'off_requests', ['status'], unique=False)
    op.create_index(op.f('ix_timesheets_period_end'), 'timesheets', ['period_end'], unique=False)
    op.create_index(op.f('ix_timesheets_period_start'), 'timesheets', ['period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_period_start'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_period_end'), table_name='timesheets')
    op.drop_index(op.f('ix_off_requests_status'), table_name='off_requests')
    op.drop_index(op.f('ix_off_requests_start_date'), table_name='off_requests')
    op.drop_index(op.f('ix_off_requests_end_date'), table_name='off_requests')
    op.drop_index(op.f('ix_attendance_daily_period_start'), table_name='attendance_daily')
    op.drop_index(op.f('ix_attendance_daily_period_end'), table_name='attendance_daily')
    # ### end Alembic commands ###

