"""add_created_at_updated_at_to_employees

Revision ID: 80201bbef4f0
Revises: 91c633ad1258
Create Date: 2026-06-09 15:16:51.271991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80201bbef4f0'
down_revision: Union[str, None] = '91c633ad1258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_daily', 'period_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('attendance_daily', 'period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('attendance_daily', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('attendance_daily', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.alter_column('attendance_daily', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('attendance_daily', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('attendance_daily', 'period_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('attendance_daily', 'period_start',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###

