"""add_auth_and_publish

Revision ID: 91c633ad1258
Revises: f430f4c08d93
Create Date: 2026-06-09 10:06:21.458459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c633ad1258'
down_revision: Union[str, None] = 'f430f4c08d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_engine='InnoDB',
        mysql_charset='utf8mb4',
        mysql_collate='utf8mb4_unicode_ci',
        )
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Add user_id to employees if not already present
    emp_cols = [c['name'] for c in inspector.get_columns('employees')]
    if 'user_id' not in emp_cols:
        op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # Add is_published to monthly_salary_inputs if not already present
    msi_cols = [c['name'] for c in inspector.get_columns('monthly_salary_inputs')]
    if 'is_published' not in msi_cols:
        op.add_column('monthly_salary_inputs', sa.Column('is_published', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_salary_inputs', 'is_published')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

