"""Add SalaryDecision

Revision ID: 93d414c70b13
Revises: 2b1e90f7f3ca
Create Date: 2026-07-06 10:43:32.932608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d414c70b13'
down_revision: Union[str, None] = '2b1e90f7f3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_salary', sa.Integer(), nullable=False),
    sa.Column('new_salary', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_decisions_employee_id'), 'salary_decisions', ['employee_id'], unique=False)
    op.add_column('monthly_salary_inputs', sa.Column('is_mid_month_change', sa.Boolean(), nullable=False))
    op.add_column('monthly_salary_inputs', sa.Column('prorated_old_salary', sa.Integer(), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('prorated_new_salary', sa.Integer(), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('prorated_days_old', sa.Float(), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('prorated_days_new', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_salary_inputs', 'prorated_days_new')
    op.drop_column('monthly_salary_inputs', 'prorated_days_old')
    op.drop_column('monthly_salary_inputs', 'prorated_new_salary')
    op.drop_column('monthly_salary_inputs', 'prorated_old_salary')
    op.drop_column('monthly_salary_inputs', 'is_mid_month_change')
    op.drop_index(op.f('ix_salary_decisions_employee_id'), table_name='salary_decisions')
    op.drop_table('salary_decisions')
    # ### end Alembic commands ###

