"""add_allowances_to_decision_and_employee

Revision ID: 9c8513f9d9a0
Revises: f6683f8431f9
Create Date: 2026-07-07 10:38:57.703811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8513f9d9a0'
down_revision: Union[str, None] = 'f6683f8431f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('meal_allowance', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('trans_allowance', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('phone_allowance', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('other_allowance', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('bonus_coefficient', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('salary_decisions', sa.Column('meal_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_decisions', sa.Column('trans_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_decisions', sa.Column('phone_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_decisions', sa.Column('other_allowance', sa.Integer(), nullable=False))
    op.add_column('salary_decisions', sa.Column('bonus_coefficient', sa.Numeric(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_decisions', 'bonus_coefficient')
    op.drop_column('salary_decisions', 'other_allowance')
    op.drop_column('salary_decisions', 'phone_allowance')
    op.drop_column('salary_decisions', 'trans_allowance')
    op.drop_column('salary_decisions', 'meal_allowance')
    op.drop_column('employees', 'bonus_coefficient')
    op.drop_column('employees', 'other_allowance')
    op.drop_column('employees', 'phone_allowance')
    op.drop_column('employees', 'trans_allowance')
    op.drop_column('employees', 'meal_allowance')
    # ### end Alembic commands ###

