"""add_bonus_14

Revision ID: b168f9dae9a5
Revises: 80201bbef4f0
Create Date: 2026-06-10 19:51:03.980355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b168f9dae9a5'
down_revision: Union[str, None] = '80201bbef4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_salary_inputs', sa.Column('bonus_14', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_salary_inputs', 'bonus_14')
    # ### end Alembic commands ###

