"""Add tax_code, phone_number, social_insurance_number

Revision ID: c24b11595164
Revises: 6ab2ee9049c6
Create Date: 2026-07-03 13:53:49.853861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24b11595164'
down_revision: Union[str, None] = '6ab2ee9049c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('tax_code', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('social_insurance_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'social_insurance_number')
    op.drop_column('employees', 'phone_number')
    op.drop_column('employees', 'tax_code')
    # ### end Alembic commands ###

