"""add commission rep overrides

Revision ID: c95d1beea36b
Revises: df41c3f2edd3
Create Date: 2026-06-24 09:44:37.564779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95d1beea36b'
down_revision: Union[str, None] = 'df41c3f2edd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_rep_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('sales_rep', sa.String(length=150), nullable=False),
    sa.Column('override_job_count', sa.Integer(), nullable=True),
    sa.Column('override_profit_loss', sa.Float(), nullable=True),
    sa.Column('override_target', sa.Float(), nullable=True),
    sa.Column('override_bonus_rate', sa.Float(), nullable=True),
    sa.Column('override_total_bonus', sa.Float(), nullable=True),
    sa.Column('override_monthly_bonus', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['commission_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'sales_rep', name='uq_period_sales_rep')
    )
    op.create_index(op.f('ix_commission_rep_overrides_period_id'), 'commission_rep_overrides', ['period_id'], unique=False)
    op.create_index(op.f('ix_commission_rep_overrides_sales_rep'), 'commission_rep_overrides', ['sales_rep'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commission_rep_overrides_sales_rep'), table_name='commission_rep_overrides')
    op.drop_index(op.f('ix_commission_rep_overrides_period_id'), table_name='commission_rep_overrides')
    op.drop_table('commission_rep_overrides')
    # ### end Alembic commands ###

