"""add_salary_period_overrides_and_employee_dates

Revision ID: c9f05440e7f5
Revises: b168f9dae9a5
Create Date: 2026-06-11 16:02:36.785439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f05440e7f5'
down_revision: Union[str, None] = 'b168f9dae9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('resignation_period', sa.String(length=7), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('fullname', sa.String(length=150), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('contract_salary', sa.Integer(), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('employee_type', sa.String(length=50), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('position', sa.String(length=150), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('dependents_count', sa.Integer(), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.add_column('monthly_salary_inputs', sa.Column('bank_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_salary_inputs', 'bank_name')
    op.drop_column('monthly_salary_inputs', 'account_number')
    op.drop_column('monthly_salary_inputs', 'dependents_count')
    op.drop_column('monthly_salary_inputs', 'position')
    op.drop_column('monthly_salary_inputs', 'employee_type')
    op.drop_column('monthly_salary_inputs', 'contract_salary')
    op.drop_column('monthly_salary_inputs', 'fullname')
    op.drop_column('employees', 'resignation_period')
    op.drop_column('employees', 'start_date')
    # ### end Alembic commands ###

