"""add_commission_tables

Revision ID: df41c3f2edd3
Revises: f19f182c444f
Create Date: 2026-06-23 08:39:44.337223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df41c3f2edd3'
down_revision: Union[str, None] = 'f19f182c444f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_label', sa.String(length=30), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('till_date', sa.Date(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('job_no', sa.String(length=50), nullable=False),
    sa.Column('job_date', sa.Date(), nullable=True),
    sa.Column('hbl', sa.String(length=100), nullable=True),
    sa.Column('mbl', sa.String(length=100), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('sales_rep', sa.String(length=150), nullable=True),
    sa.Column('shipper', sa.String(length=255), nullable=True),
    sa.Column('consignee', sa.String(length=255), nullable=True),
    sa.Column('sub_type', sa.String(length=50), nullable=True),
    sa.Column('container_string', sa.String(length=100), nullable=True),
    sa.Column('wt', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('carrier_booking_no', sa.String(length=100), nullable=True),
    sa.Column('por', sa.String(length=100), nullable=True),
    sa.Column('final_destination', sa.String(length=100), nullable=True),
    sa.Column('realized_revenue', sa.Float(), nullable=False),
    sa.Column('unrealized_revenue', sa.Float(), nullable=False),
    sa.Column('realized_cost', sa.Float(), nullable=False),
    sa.Column('unrealized_cost', sa.Float(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=False),
    sa.Column('container_picked', sa.String(length=10), nullable=True),
    sa.Column('payment_received', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['commission_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_jobs_job_no'), 'commission_jobs', ['job_no'], unique=False)
    op.create_index(op.f('ix_commission_jobs_period_id'), 'commission_jobs', ['period_id'], unique=False)
    op.create_index(op.f('ix_commission_jobs_sales_rep'), 'commission_jobs', ['sales_rep'], unique=False)
    op.drop_constraint('upload_batches_ibfk_1', 'upload_batches', type_='foreignkey')
    op.create_foreign_key(None, 'upload_batches', 'users', ['uploaded_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_batches', type_='foreignkey')
    op.create_foreign_key('upload_batches_ibfk_1', 'upload_batches', 'employees', ['uploaded_by_user_id'], ['id'])
    op.drop_index(op.f('ix_commission_jobs_sales_rep'), table_name='commission_jobs')
    op.drop_index(op.f('ix_commission_jobs_period_id'), table_name='commission_jobs')
    op.drop_index(op.f('ix_commission_jobs_job_no'), table_name='commission_jobs')
    op.drop_table('commission_jobs')
    op.drop_table('commission_periods')
    # ### end Alembic commands ###

