"""Add HolidaySetting and TimesheetPeriod

Revision ID: e863d7acf11b
Revises: 54c9148a2c11
Create Date: 2026-07-08 10:19:02.886258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e863d7acf11b'
down_revision: Union[str, None] = '54c9148a2c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holiday_settings_holiday_date'), 'holiday_settings', ['holiday_date'], unique=True)
    op.create_table('timesheet_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', 'period_end', name='uq_timesheet_periods_start_end')
    )
    op.create_index(op.f('ix_timesheet_periods_period_end'), 'timesheet_periods', ['period_end'], unique=False)
    op.create_index(op.f('ix_timesheet_periods_period_start'), 'timesheet_periods', ['period_start'], unique=False)
    op.create_index('ix_timesheet_periods_start_end', 'timesheet_periods', ['period_start', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timesheet_periods_start_end', table_name='timesheet_periods')
    op.drop_index(op.f('ix_timesheet_periods_period_start'), table_name='timesheet_periods')
    op.drop_index(op.f('ix_timesheet_periods_period_end'), table_name='timesheet_periods')
    op.drop_table('timesheet_periods')
    op.drop_index(op.f('ix_holiday_settings_holiday_date'), table_name='holiday_settings')
    op.drop_table('holiday_settings')
    # ### end Alembic commands ###

