"""Add mid_month_effective_date to monthly_salary_inputs

Revision ID: f6683f8431f9
Revises: 93d414c70b13
Create Date: 2026-07-06 11:29:36.508093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6683f8431f9'
down_revision: Union[str, None] = '93d414c70b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_salary_inputs', sa.Column('mid_month_effective_date', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_salary_inputs', 'mid_month_effective_date')
    # ### end Alembic commands ###

